config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'thread_comments/show'
  end
  scope module: :public do
    devise_for :end_users, controllers: {
      sessions: 'public/end_users/sessions',
      registrations: 'public/end_users/registrations'
    }
    root 'home#home'
    resources :end_users, only: [:index, :show, :edit, :update]
    resources :lists, only: [:show, :create, :edit, :update, :destroy] do 
      resources :list_elements, only: [:new, :create, :update, :destroy] do
        collection { post :import }
      end
      resources :cheap_threads, only: %i(create new), path: :threads
      get 'gacha/default', to: 'gachas#default', as: :gacha_default
      get 'gacha/price', to: 'gachas#price', as: :gacha_price
      get 'gacha/calorie', to: 'gachas#calorie', as: :gacha_calorie
      post 'gacha/default', to: 'gachas#default_create', as: :gacha_default_create
      post 'gacha/price', to: 'gachas#price_create', as: :gacha_price_create
      post 'gacha/calorie', to: 'gachas#calorie_create', as: :gacha_calorie_create
    end
    resources :cheap_threads, only: %i(index show), path: :threads do
      resources :thread_comments, only: %i(show create), path: :comments
    end
    post 'home/sort', to: 'home#sort', as: :home_sort
    post 'lists/search', to: 'lists#search', as: :search_list
  end

  namespace :admin do
    devise_for :admins,
    path: '', controllers: {
      sessions: 'admin/admins/sessions'
    }
    get '/' => 'home#top'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      resources :lists, only: [:index, :show] do
        resources :list_elements, only: [:index], path: :elements
        get 'gacha/default', to: 'gachas#default'
        get 'gacha/price', to: 'gachas#price'
        get 'gacha/calorie', to: 'gachas#calorie'
      end
    end
  end
end

app/views/layouts/_admin_header.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
            <%= link_to "", class:"navbar-brand", style: "color: yellow;" do%>
                <span>〇円ガチャ(仮)(管理者)</span>
            <% end %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav navbar-right ml-auto">
                    <li><%= link_to "ホーム", "/", class: "fas fa-home nav-link text-light"%></li>
                    <li><%= link_to "リスト一覧", "/", class: "fas fa-list nav-link text-light"%></li>
                    <% if admin_admin_signed_in? %>
                    <li><%= link_to "ログアウト", destroy_admin_admin_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light"%></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/_public_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
            <%= link_to "", class:"navbar-brand", style: "color: yellow; font-size: 24px;" do%>
                <%= image_tag 'logo_gacha.jpeg', size: '50x50'%>
            <% end %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav navbar-right ml-auto">
                    <li><%= link_to "ホーム", "/", class: "fas fa-home nav-link text-light"%></li>
                    <li><%= link_to "ユーザ一覧", end_users_path, class: "fas fa-users nav-link text-light"%></li>
                    <li><%= link_to "公開ガチャ一覧", "/", class: "fas fa-list nav-link text-light"%></li>
                    <% if end_user_signed_in? %>
                    <li><%= link_to "マイページ", end_user_path(current_end_user), class: "far fa-user nav-link text-light"%></li>
                    <li><%= link_to "ログアウト", destroy_end_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light"%></li>
                    <% else %>
                    <li><%= link_to "アカウント作成", new_end_user_registration_path, class: "fas fa-user-plus nav-link text-light"%></li>
                    <li><%= link_to "ログイン",  new_end_user_session_path, class: "fas fa-sign-in-alt nav-link text-light"%></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin_Cheapthread</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/a3ed360f29.js" crossorigin="anonymous"></script>
   
  </head>

  <body>

    <%= render 'layouts/admin_header'%>

    <p id="notice"><%= notice %></p>
    
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<%= content_for?(:content) ? yield(:content) : yield %>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title><%= content_for?(:title) ? yield(:title) : "何でもガチャ"%></title>
    <meta name="twitter:card" content="summary" />
    <meta property="og:url" content=<%= content_for?(:sns_url) ? yield(:sns_url) : "https://cheapthread.jp/" + request.fullpath %> /> 
    <meta property="og:title" content=<%= content_for?(:sns_title) ? yield(:sns_title) : "何でもガチャ" %> /> 
    <meta property="og:description" content=<%= content_for?(:sns_description) ? yield(:sns_description) : "○円ガチャや○kcalガチャを気軽に作ったり回したりできるサイトです。また、任意のリストをもとに安価スレを作成し自動でスレを投げてくれる勝手に安価スレ機能も有ります" %> /> 
    <meta property="og:image" content=<%= content_for?(:sns_image) ? yield(:sns_image) : "https://cheapthread.jp/" + image_url("logo_gacha.jpeg") %> /> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/a3ed360f29.js" crossorigin="anonymous"></script>
   
  </head>

  <body>

    <%= render "layouts/public_header"%>

    <p id="notice"><%= notice %></p>
    
    <%= yield %>
    <footer style="margin-top: 100px;"></footer>

    
  </body>
</html>